### ISSUE TITLE
yolo_v3.cfg file missed

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#2]
Hello, 
IT is a great work I appreciate it. when I use the default yolov3 file from internet I face some problems such as:

```
Traceback (most recent call last):
  File "/home/pc4193/zeyn/random_repos/Aerial-Vision-and-Dialog-Navigation/src/xview_et/main.py", line 314, in <module>
    main()
  File "/home/pc4193/zeyn/random_repos/Aerial-Vision-and-Dialog-Navigation/src/xview_et/main.py", line 310, in main
    valid(args, val_envs, val_full_traj_envs, rank=rank)
  File "/home/pc4193/zeyn/random_repos/Aerial-Vision-and-Dialog-Navigation/src/xview_et/main.py", line 257, in valid
    agent = agent_class(args, rank=rank)
  File "/home/pc4193/zeyn/random_repos/Aerial-Vision-and-Dialog-Navigation/src/xview_et/agent.py", line 141, in __init__
    self.vision_model.load_state_dict(state)
  File "/home/pc4193/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Darknet:
	size mismatch for module_list.81.conv_81.weight: copying a param with shape torch.Size([650, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 1024, 1, 1]).
	size mismatch for module_list.81.conv_81.bias: copying a param with shape torch.Size([650]) from checkpoint, the shape in current model is torch.Size([255]).
	size mismatch for module_list.93.conv_93.weight: copying a param with shape torch.Size([650, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 512, 1, 1]).
	size mismatch for module_list.93.conv_93.bias: copying a param with shape torch.Size([650]) from checkpoint, the shape in current model is torch.Size([255]).
	size mismatch for module_list.105.conv_105.weight: copying a param with shape torch.Size([650, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 256, 1, 1]).
	size mismatch for module_list.105.conv_105.bias: copying a param with shape torch.Size([650]) from checkpoint, the shape in current model is torch.Size([255]).
```

Even if I change the value 255 to 650  I face different problems. Am I doing sth wrong or is it because of cfg file ? 
and if so would you be able to share the yolo_v3.cfg file please ? 
Thanks in advance

**Comment by UeFan** [comment]
Hi, the yolov3 used in our model is modified from the original yolov3. We removed several layers in the end from the original one. Here is the config file we use. https://drive.google.com/file/d/1n6RMWcHAbS6DA7BBug6n5dyN6NPjiPjh/view?usp=sharing 

I have updated the Readme accordingly. Sorry for the inconvenience.
