### ISSUE TITLE
您好，请问可以提供 checkpoints 和预训练文件的谷歌云盘链接吗？我无法通过gdown来访问它

### ISSUE THREAD

**Issue by XinyiWang1123** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#3]
Traceback (most recent call last):
  File "/root/miniconda3/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/gdown/cli.py", line 156, in main
    filename = download(
  File "/root/miniconda3/lib/python3.8/site-packages/gdown/download.py", line 161, in download
    res = sess.get(url, stream=True, verify=verify)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Ke-pA5jpq1-fsEwAch_iRCtJHx6rQc-Z (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f355786fdc0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by UeFan** [comment]
Sure. https://drive.google.com/drive/folders/1kgL8lR1UonRqhe4dEQW50o3J1c1UbggK?usp=sharing
